#配置dev环境
server:
  port: 7070

spring:
  profiles: dev
  #指定当前服务对外暴露的名称
  application:
    name: jxdmsc-consumer-depart
  #配置spring-data-jpa


eureka:
  client:
    service-url:
      defaultZone: http://eureka8400.com:8400/eureka
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

#开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true


---
#配置test环境
server:
  port: 9090

spring:
  profiles: test
  #指定当前服务对外暴露的名称
  application:
    name: jxdmsc-consumer-depart
  #配置spring-data-jpa

eureka:
  client:
    service-url:
      defaultZone: http://eureka8500.com:8500/eureka
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

#开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true